development:
  adapter: postgresql
  encoding: utf8
  database: botherbox_development
  username: botherbox
  port: 5432
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: botherbox_test
  username: botherbox
  port: 5432
  host: localhost
